"""Add CRN field to Checklist

Revision ID: 39e971d8ea61
Revises: 7996d3e3e525
Create Date: 2024-10-11 19:25:41.266275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e971d8ea61'
down_revision = '7996d3e3e525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist', sa.Column('crn', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist', 'crn')
    # ### end Alembic commands ###
