"""Manual changes reflection

Revision ID: 413345a4787c
Revises: ca281d4159d4
Create Date: 2024-10-16 11:53:28.789768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '413345a4787c'
down_revision = 'ca281d4159d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('avaliador', sa.String(length=100), nullable=False),
    sa.Column('data_inspecao', sa.Date(), nullable=False),
    sa.Column('area_observada', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('porcentagem_conformidade', sa.Float(), nullable=False),
    sa.Column('tipo_checklist', sa.String(length=50), nullable=False),
    sa.Column('crn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('conformidade', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('anexo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'questao_id', name='uq_checklist_questao')
    )
    op.drop_table('checklist')
    op.drop_index('documento', table_name='cliente')
    op.drop_table('cliente')
    op.drop_table('checklist_resposta')
    op.drop_table('documento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_arquivo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='documento_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('checklist_resposta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questao_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('conformidade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.Column('anexo', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name='checklist_resposta_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_pessoa', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('documento', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cep', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('documento', 'cliente', ['documento'], unique=True)
    op.create_table('checklist',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avaliador', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('data_inspecao', sa.DATE(), nullable=False),
    sa.Column('area_observada', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('porcentagem_conformidade', mysql.FLOAT(), nullable=False),
    sa.Column('tipo_checklist', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('crn', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='checklist_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('checklist_respostas')
    op.drop_table('documentos')
    op.drop_table('checklists')
    op.drop_table('clientes')
    # ### end Alembic commands ###
