"""Adicionar tipo_checklist ao modelo Checklist

Revision ID: 9db8bb102433
Revises: f5ffe2870d17
Create Date: 2024-10-09 15:27:59.716643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db8bb102433'
down_revision = 'f5ffe2870d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns('checklist')
    if 'tipo_checklist' not in [col['name'] for col in columns]:
        op.add_column('checklist', sa.Column('tipo_checklist', sa.String(length=50), nullable=True))
        op.execute("UPDATE checklist SET tipo_checklist = 'default_type' WHERE tipo_checklist IS NULL")
        op.alter_column('checklist', 'tipo_checklist', nullable=False)
    
    # Adicione a chave estrangeira apenas se ela ainda não existir
    if 'cliente_id' not in [fk['constrained_columns'][0] for fk in inspector.get_foreign_keys('checklist')]:
        op.create_foreign_key(None, 'checklist', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklist', type_='foreignkey')
    op.drop_column('checklist', 'tipo_checklist')
    # ### end Alembic commands ###
