"""Adicionar tipo_checklist ao modelo Checklist

Revision ID: bc0dc724c91d
Revises: 636b1af470ee
Create Date: 2024-10-10 13:21:48.506752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0dc724c91d'
down_revision = '636b1af470ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('checklist', 'porcentagem_conformidade',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_column('checklist', 'data_criacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist', sa.Column('data_criacao', sa.DATETIME(), nullable=True))
    op.alter_column('checklist', 'porcentagem_conformidade',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('checklist', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
