"""Adicionar campo porcentagem_conformidade ao Checklist

Revision ID: f5ffe2870d17
Revises: 
Create Date: 2024-10-08 15:51:53.697931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ffe2870d17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('porcentagem_conformidade', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('porcentagem_conformidade')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
